#!/usr/bin/env python3
"""Render the reviewable Markdown view of the controlled vocabulary contract."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any

from validate_controlled_vocabulary import DEFAULT_CONTRACT, ContractError, load_contract, validate_contract


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "docs" / "CONTROLLED_VOCABULARY.md"
ACTOR_MEANINGS = {
    "system": "Trusted API/domain code performing a deterministic policy action; never an AI or external provider.",
    "worker": "The authenticated background worker executing an idempotent job by identifier.",
    "reviewer": "An authenticated, authorised human reviewer.",
    "admin": "An authenticated human administrator with explicitly broader correction authority.",
    "reporter": "The holder of the report tracking credential answering an approved follow-up; not a public account.",
}
MACHINE_GUARDS = {
    "project_public_status": "Approved citation, effective/checked date, optimistic concurrency, and append-only project update are required. Discovery, AI, and report status cannot invoke it.",
    "source_review_state": "Provenance, exact passage, rights/reuse note, availability, reviewer identity, and decision reason are recorded. Approval scope is explicit.",
    "source_availability": "A bounded safe fetch result or reviewer evidence and checked time are recorded. Availability never changes fact verification by implication.",
    "verification_state": "The fact/update and supporting approved citation set are locked and validated in one transaction. Conflicts remain visible.",
    "report_risk_level": "Risk reasons stay private. Automation may only raise from standard; only a reviewer/admin may lower or revise an elevated result.",
    "report_status": "Authorisation, current-version match, permitted transition, public-safe message, status event, and audit event succeed atomically. No transition publishes report content.",
    "evidence_sanitation_state": "Input limits and sniffed type pass before processing; raw temporary content is deleted on every outcome; only a sanitised derivative may persist.",
    "malware_scan_state": "Scanning applies to the sanitised derivative. Required-scan failure keeps it unavailable. not_scanned_demo is accepted only for the fictional hosted demo and is forbidden in production.",
    "discovery_status": "The actor has scope access, the run version/lease matches, and the job is idempotent. Cancellation stops future fetches but preserves already retrieved review records.",
    "discovered_source_disposition": "A human records a reason. attach enters the ordinary pending source-review workflow; it never approves a fact or publishes a result.",
    "translation_status": "Status is tied to the exact source-text version. reviewed requires a recorded fluent human reviewer; a source-text change invalidates prior approval.",
}
CLASSIFICATION_POLICIES = {
    "project_category": "A reviewer/admin may reclassify with reason and audit history. Existing public URLs and historical events remain stable.",
    "information_class": "Derived from source origin and review context; it has no direct public mutation command.",
    "source_type": "A reviewer/admin may correct the preliminary type with reason and audit history; type never implies approval or verification.",
    "report_concern_category": "The reporter selects it at submission. A reviewer/admin may reclassify privately with reason; the original submission remains in audit history.",
}


def humanise(value: str) -> str:
    return value.replace("_", " ").capitalize()


def code(value: str) -> str:
    return f"`{value}`"


def render(contract: dict[str, Any]) -> str:
    lines = [
        "<!-- GENERATED by scripts/render_controlled_vocabulary.py from contracts/controlled-vocabulary.json. DO NOT EDIT BY HAND. -->",
        "",
        "# Controlled vocabulary and state machines",
        "",
        f"- **Contract:** `{contract['contract_id']}` schema version {contract['schema_version']}",
        f"- **Effective date:** {contract['effective_date']}",
        "- **Authority:** `contracts/controlled-vocabulary.json` is the machine-readable source for database constraints, Pydantic types, OpenAPI examples, translation keys, and fixtures.",
        "- **Validation:** `python3 scripts/validate_controlled_vocabulary.py --self-test`",
        "- **Drift check:** `python3 scripts/render_controlled_vocabulary.py --check`",
        "",
        "## Contract rules",
        "",
        "- Machine values are lowercase snake-case, immutable after release, and scoped by their named field. A value cannot carry two meanings within one field.",
        "- APIs and persistence use machine values. Interfaces use locale keys shaped as `vocabulary.<field>.<value>` and never translate or title-case the machine value at runtime.",
        "- An unlisted value is invalid. Unknown external input produces a stable boundary error; it is never coerced to a nearby state.",
        "- Source availability and fact verification are independent. An unavailable source does not erase historical verification, and an available source is not automatically verified.",
        "- Project status describes what approved evidence establishes. It is not a truth score, delivery-quality judgment, or accusation.",
        "- State changes use compare-and-set or row locking, append an audit event, and commit their domain effect atomically. Repeating an idempotency key cannot append a second event.",
        "- AI, search providers, and workers cannot perform human-review or publication transitions. Worker-labelled transitions are deterministic processing outcomes only.",
        "- Public visibility describes the maximum safe projection of the transition; it never authorises raw private data or automatic publication.",
        "",
        "## Actors",
        "",
        "| Machine value | Authority |",
        "| --- | --- |",
    ]
    for actor in contract["actors"]:
        lines.append(f"| {code(actor)} | {ACTOR_MEANINGS[actor]} |")

    lines.extend(["", "## Value catalogue", ""])
    for name, definition in contract["vocabularies"].items():
        lines.extend(
            [
                f"### {code(name)}",
                "",
                f"Kind: **{definition['kind']}**. Change policy: {code(definition['change_policy'])}.",
                "",
                "| Machine value | Meaning |",
                "| --- | --- |",
            ]
        )
        for item in definition["values"]:
            lines.append(f"| {code(item['value'])} | {item['meaning']} |")
        lines.append("")

    lines.extend(
        [
            "## Classification mutation policy",
            "",
            "Classifications are not lifecycle states, so they have no terminal states or automatic transitions.",
            "",
            "| Field | Mutation rule |",
            "| --- | --- |",
        ]
    )
    for name, policy in CLASSIFICATION_POLICIES.items():
        lines.append(f"| {code(name)} | {policy} |")

    lines.extend(
        [
            "",
            "## State-machine summary",
            "",
            "An empty terminal-state set is deliberate. `closed` is quiescent, not irreversible, because reopening must remain explicit and auditable.",
            "",
            "| Machine | Initial state | Terminal states | Quiescent states | Failure code | Mandatory guards and effects |",
            "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    for name, machine in contract["state_machines"].items():
        definition = contract["vocabularies"][name]
        terminal = ", ".join(code(value) for value in definition["terminal_states"]) or "None"
        quiescent = ", ".join(code(value) for value in definition.get("quiescent_states", [])) or "None"
        lines.append(
            f"| {code(name)} | {code(definition['initial_state'])} | {terminal} | {quiescent} | {code(machine['failure_code'])} | {MACHINE_GUARDS[name]} |"
        )

    lines.extend(
        [
            "",
            "## Consolidated transition contract",
            "",
            "This is the single transition table used to answer current state, command, authorised actor, next state, audit event, visibility, and stable failure code. A missing row is forbidden. Self-transitions are not state changes and must not append history.",
            "",
            "| Machine | Current state | Command | Actor(s) | Next state | Audit event | Public visibility | Failure code |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for name, machine in contract["state_machines"].items():
        failure_code = machine["failure_code"]
        for transition in machine["transitions"]:
            actors = ", ".join(code(actor) for actor in transition["actors"])
            lines.append(
                "| "
                + " | ".join(
                    [
                        code(name),
                        code(transition["from"]),
                        code(transition["command"]),
                        actors,
                        code(transition["to"]),
                        code(transition["audit_event"]),
                        code(transition["public_visibility"]),
                        code(failure_code),
                    ]
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "## Required implementation derivation",
            "",
            "For every field in this contract, the implementing task must:",
            "",
            "1. generate or import the backend enum/literal from the JSON contract rather than retyping values;",
            "2. create a named database `CHECK` constraint from the same value set;",
            "3. expose only the relevant values and examples in OpenAPI, then regenerate the TypeScript client;",
            "4. provide all four locale keys with parity checks and explicit translation status;",
            "5. build positive and negative fixtures from the state-machine rows;",
            "6. test unauthorised actors, stale versions, missing guards, every forbidden edge, and terminal-state immutability; and",
            "7. update this contract first when a value changes, then include migration, compatibility, UI-copy, fixture, and audit-event changes in the same review.",
            "",
            "A released value is never silently renamed or repurposed. Replacement requires an ADR, a data/API migration, a deprecation window where applicable, and a new machine value.",
            "",
        ]
    )
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--contract", type=Path, default=DEFAULT_CONTRACT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the committed Markdown is stale")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        contract = load_contract(args.contract)
        validate_contract(contract)
    except ContractError as error:
        print(f"controlled vocabulary render: FAIL: {error}", file=sys.stderr)
        return 1

    rendered = render(contract)
    if args.check:
        try:
            current = args.output.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"controlled vocabulary render: FAIL: missing {args.output}", file=sys.stderr)
            return 1
        if current != rendered:
            print(f"controlled vocabulary render: FAIL: stale {args.output}", file=sys.stderr)
            return 1
        print(f"controlled vocabulary render: OK ({args.output})")
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    print(f"controlled vocabulary render: wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
